---
title: "ASTRUC"
author: "Jean-Baptiste Astruc"
format: html
---

# Main data set import

## Question 1

We created a data folder to store the files.

## Question 2

[Here](https://github.com/JBA15/stars) is the URL to the repository containing the project on Github.

```{r}
#| message: false
here::i_am("stars.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
```

## Question 3

Let's load the main data set.

```{r}
planets <- vroom(here("data", "all-planets.csv"),
                 na = "Unknown",
                 locale = locale(decimal_mark = ","),
                 col_types = cols(
                   Planet_key = col_double(),
                   planet = col_character(),
                   STAR_CODE = col_double(),
                   `relative mass` = col_double(),
                   `Relative Density` = col_double(),
                   `RADIUS (EARTH)` = col_double(),
                   `Type Of Terrain` = col_character(),
                   `Climate Type` = col_character()
                 ))
```

```{r}
if (nrow(planets) == 902 & ncol(planets) == 8) {
  print("The loading process went great!")
} else {
  print("The loading process did not go well!")
}
```
Moreover, we loaded the data in order to have numerical variables recognised as numerical variables.

## Question 4

```{r}
num_planets <- nrow(planets)
num_variables <- ncol(planets)
```

```{r}
sum_na_planet_key <- planets[["planet_key"]] |>
  is.na() |>
  sum()

sum_na_planet <- planets[["planet"]] |>
  is.na() |>
  sum()

sum_na_code <- planets[["STAR_CODE"]] |>
  is.na() |>
  sum()

sum_na_mass <- planets[["relative mass"]] |>
  is.na() |>
  sum()

sum_na_density <- planets[["Relative Density"]] |>
  is.na() |>
  sum()

sum_na_radius <- planets[["RADIUS (EARTH)"]] |>
  is.na() |>
  sum()

sum_na_terrain <- planets[["Type of terrain"]] |>
  is.na() |>
  sum()

sum_na_climate <- planets[["Climate Type"]] |>
  is.na() |>
  sum()
```




```{r}
planets_summary <- data.frame(
  Attribute = c("Number of planets", 
                "Number of variables",
                "Number of missing values in relative density",
                "Number of missing values in relative mass"),
  Value = c(
    num_planets,
    num_variables,
    sum_na_density,
    sum_na_mass
  )
)
knitr::kable(planets_summary, caption = "Check for the validity of the loading process for planets")
```

## Question 5

```{r}
planets_no_na <- planets |>
  drop_na(`relative mass`) |>
  drop_na(`Relative Density`) |>
  drop_na(`RADIUS (EARTH)`)

ggplot(planets_no_na, aes(x = `Relative Density`, y = `relative mass`)) +
  geom_point()
```

## Question 6

```{r}
max_mass <- planets_no_na[order(planets_no_na$`relative mass`),] |>
  slice_tail() |>
  select(planet)

max_density <- planets_no_na[order(planets_no_na$`Relative Density`),] |>
  slice_tail() |>
  select(planet)

max_radius <- planets_no_na[order(planets_no_na$`RADIUS (EARTH)`),] |>
  slice_tail() |>
  select(planet)

min_mass <- planets_no_na[order(planets_no_na$`relative mass`),] |>
  slice_head() |>
  select(planet)

min_density <- planets_no_na[order(planets_no_na$`Relative Density`),] |>
  slice_head() |>
  select(planet)

min_radius <- planets_no_na[order(planets_no_na$`RADIUS (EARTH)`),] |>
  slice_head() |>
  select(planet)
```


```{r}
planets_outliers <- data.frame(
  Attribute = c("Max mass", 
                "Max density",
                "Max radius",
                "Min mass",
                "Min density",
                "Min radius"),
  Value = c(
    max_mass,
    max_density,
    max_radius,
    min_mass,
    min_density,
    min_radius
  )
)

knitr::kable(planets_outliers, caption = "The outliers")

```

# Improved data representation

## Question 7

```{r}

```


























